name: jazzy
on:
  push:
    branches:
      - 'main'
      - 'jazzy'
  pull_request:
    branches:
      - 'main'
      - 'jazzy'
  workflow_dispatch:
    branches:
      - '*'
jobs:
  ros_jazzy:
    name: jazzy
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build and Test
        uses: ros-tooling/action-ros-ci@0.3.13
        with:
          target-ros2-distro: jazzy
          vcs-repo-file-url: $GITHUB_WORKSPACE/source_dependencies.yaml
          rosdep-check: true